name = "my-post-purchase-ui-extension"
type = "checkout_post_purchase"
uid = "f4f18f33-70b3-5b25-0d55-cd88c77f38c1"

[capabilities]
network_access = true

[network_access]
allowed_urls = [
  "https://post-purchase-pro-app.vercel.app",
]